{"__error": {"error_code": "shareclasses-12345", "status": 404, "user_message": "Nothing Found against provided ID.", "user_error_code": "12345", "correlation_id": "764af451-fffb-46f8-ac69-a65c0fa1ea8f", "message": "0 records Found. Please check your URL", "more_info": "", "additional_info": ["Traceback(most recent call last):\n", "  File `/var/task/lambdas/data_access_service_system_api/system_api_manager_shareclass.py`, line 103, in lambda_handler\n    user_message=ApplicationErrors.EDL_ERROR_MESSAGE_USER_NO_RECORDS_FOUND)\n", "Error Type -> NoRecordsFoundException"]}}